### ISSUE TITLE
Primary key is not getting automated

### ISSUE THREAD

**Issue by mohitsoni2111** [mohitsoni2111/jobPortal#8]
The primary key is not getting auto-updated in the CompanyInfo class.

**Comment by akshat22** [comment]
`public static final String INSERT_COMPANY_SQL = "INSERT INTO JOBPORTAL.DASHBOARD VALUES (?, ?, ?, ?, ?, ?);";` should be `public static final String INSERT_COMPANY_SQL = "INSERT INTO JOBPORTAL.DASHBOARD(col_name_1, col_name_2, ...) VALUES (?, ?, ?, ?, ?, ?);";` since the id column in the database is set to autogenerate. That's why you will have to mention column name with the above Insert Query.

**Comment by mohitsoni2111** [comment]
The issue has been resolved.
